name: workoutdiary
description: Record your exercise on one page per day and analyze your exercise records over time
publish_to: none
version: 1.4.3+15
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localization: ^0.1.14
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  fl_chart: ^0.65.0
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.8.0
  readmore: ^2.1.0
  intl: ^0.18.1
  uuid: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  provider: ^6.0.5
  image_cropper: ^5.0.0
  flutter_switch: ^0.3.2
  google_mobile_ads: ^3.0.0
  url_launcher: ^6.1.14
  device_info_plus: ^9.0.3
  package_info_plus: ^5.0.1
  webview_flutter: ^4.3.0
  table_calendar: ^3.0.9
  app_tracking_transparency: ^2.0.4
  flutter_native_splash: ^2.3.4
  change_app_package_name: ^1.1.0
  timer_builder: ^2.0.0
  youtube_player_flutter: ^8.1.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
flutter_native_splash:
  andriod: true
  ios: true
  web: false
  background_image: assets/img/backgroundimg.png
  image: assets/img/iconremovebg.png
  branding: assets/img/brandingImg.png
  andriod_12:
    background_image: assets/img/backgroundimg.png
    image: assets/img/iconremovebg.png
    branding: assets/img/brandingImg.png
    background_image_dark: assets/img/backgroundimg.png
    image_dark: assets/img/iconremovebg.png
    branding_dark: assets/img/brandingImg.png
dependency_overrides:
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/workoutType/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700